### ISSUE TITLE
Request: CSVs of predictions+tags

### ISSUE THREAD

**Issue by oliverdutton** [yassermb/DLA-Mutation#1]
Hello,
Interesting work. Could you please add:
- .csv of the id's [pdbid, chain, mutant] of the S2003
- .csv of data behind the figures (in particular figure 3C)
![image](https://github.com/yassermb/DLA-Mutation/assets/44170519/4444dbf4-8155-47c5-99ca-e44d7f3f993b)

**Comment by yassermb** [comment]
Hi Oliver,

Thank you for your interest in the work. Sure, I will put them this evening.

**Comment by oliverdutton** [comment]
Thank you very much
